### ISSUE TITLE
mprof script not runnable on windows

### ISSUE THREAD

**Issue by Agrisolum** [pythonprofilers/memory_profiler#75]
After installing 64bit python 2.7 memory_profiler, there is a file 'mprof' in <python>/Scripts but this is not runnable on windows.

**Comment by Tset-Noitamotua** [comment]
@Agrisolum : do I understand you right?

1. I have to rename the file `mprof` (which is in `Scripts` folder of Python after installation) to `mprof.py`? 
2. I have to put a `mprof.bat` with above mentioned content into the same folder?

Cheers
Tset

**Comment by Tset-Noitamotua** [comment]
I did it as stated above and it works! Thanks a lot!

**Comment by pankon** [comment]
Agrisolum, it works! Thanks

**Comment by pankon** [comment]
Might have to add the python folder to the batch file path though to run it from cmd

**Comment by vi3mool** [comment]
@pankon what do you mean? could you give an example please?

**Comment by pankon** [comment]
I was trying to the batch file above, I remember, from a Windows standard
command prompt, and wasn't able to until I added this folder to the
executable path. Windows searches paths for executables in a manner similar
to python searches for libraries.
This library is very helpful in benchmarking, thanks a ton!

On May 20, 2017 18:38, "vi3mool" <notifications@github.com> wrote:

@pankon <https://github.com/pankon> what do you mean? could you give an
example please?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fabianp/memory_profiler/issues/75#issuecomment-302880577>,
or mute the thread

**Comment by Juanlu001** [comment]
This can probably be closed.

**Comment by carlodri** [comment]
Switching to using python entry points should help, I'll try to submit a PR

**Comment by Juanlu001** [comment]
For anybody subscribing to this issue, latest development version of memory_profiler gained better support on Windows. Please check it out and tell us what you think.
